function c11(t_out1, YMatrix1)
%CREATEFIGURE(T_OUT1,YMATRIX1)
%  T_OUT1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 02-May-2018 21:53:12

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(t_out1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'LineStyle','-.','DisplayName','y轴');
set(plot1(2),'LineStyle','--','DisplayName','z轴');
set(plot1(3),'DisplayName','x轴');

% Create xlabel
xlabel('仿真时间t (s)','FontSize',14);

% Create ylabel
ylabel('速度变化v (m/s)','FontSize',14);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.716423574875112 0.70177314200683 0.180630630630631 0.219826602783482]);

