function c22(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-May-2018 15:33:46

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'LineStyle','-.','DisplayName','y轴');
set(plot1(2),'LineStyle','--','DisplayName','z轴');
set(plot1(3),'DisplayName','x轴');

% Create xlabel
xlabel('仿真时间t (s)','FontSize',14);

% Create ylabel
ylabel('位置变化r (m)','FontSize',14);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.752404161549522 0.722337566138188 0.108669457281812 0.178697754520766]);

