function c33(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 15-May-2018 14:31:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','幅值变化','Color',[0 0 0]);
set(plot1(2),'LineStyle','--','Color',[1 0 0],'DisplayName','速度约束');

% Create xlabel
xlabel('仿真时间 t(s)','FontSize',14);

% Create ylabel
ylabel('速度幅值 v(m/s)','FontSize',14);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.725430320515841 0.787564324939418 0.201979307242465 0.142030848329049]);

