function c_youhua(VertexNormals1, ZData1, YData1, XData1, Vertices1, Faces1, X1, Y1, Z1, X2, Y2, Z2, xdata2, ydata2, zdata2)
%CREATEFIGURE(VERTEXNORMALS1,ZDATA1,YDATA1,XDATA1,VERTICES1,FACES1,X1,Y1,Z1,X2,Y2,Z2,XDATA2,YDATA2,ZDATA2)
%  VERTEXNORMALS1:  patch vertexnormals
%  ZDATA1:  patch zdata
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data
%  X2:  vector of x data
%  Y2:  vector of y data
%  Z2:  vector of z data
%  XDATA2:  surface xdata
%  YDATA2:  surface ydata
%  ZDATA2:  surface zdata

%  Auto-generated by MATLAB on 05-May-2018 19:44:35

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12);
view(axes1,[-88 -12]);
grid(axes1,'on');
hold(axes1,'all');

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals1,'ZData',ZData1,...
    'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'LineStyle',':',...
    'Faces',Faces1,...
    'FaceColor',[1 1 1],...
    'FaceAlpha',0.01);

% Create plot3
plot3(X1,Y1,Z1,'Parent',axes1,'LineWidth',2,'Color',[1 0 0]);

% Create multiple lines using matrix input to plot3
plot31 = plot3(X2,Y2,Z2,'Parent',axes1,'MarkerSize',10,'LineStyle','none',...
    'Color',[0 0 0]);
set(plot31(1),'Marker','pentagram','DisplayName','下降飞行段终点');
set(plot31(2),'Marker','*','DisplayName','下降飞行段起点');

% Create surf
surf(xdata2,ydata2,zdata2,'Parent',axes1,'FaceAlpha',0.01);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.603975502834025 0.72597030231612 0.415862808145766 0.146907216494845],...
    'FontWeight','bold',...
    'FontSize',14);

